"""Initial enterprise schema

Revision ID: 9cddec7cec2a
Revises: 
Create Date: 2025-12-03 15:55:39.768133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cddec7cec2a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('google_email', sa.String(length=255), nullable=True),
    sa.Column('facebook_id', sa.String(length=255), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('content_generated_count', sa.Integer(), nullable=True),
    sa.Column('posts_scheduled_count', sa.Integer(), nullable=True),
    sa.Column('monthly_quota_remaining', sa.Integer(), nullable=True),
    sa.Column('quota_reset_date', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('account_locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facebook_id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('content_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('caption_template', sa.Text(), nullable=True),
    sa.Column('default_hashtags', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_by_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_templates_id'), 'content_templates', ['id'], unique=False)
    op.create_table('instagram_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instagram_user_id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_frequency_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_accounts_id'), 'instagram_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_instagram_user_id'), 'instagram_accounts', ['instagram_user_id'], unique=True)
    op.create_index(op.f('ix_instagram_accounts_next_sync_at'), 'instagram_accounts', ['next_sync_at'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_user_id'), 'instagram_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_username'), 'instagram_accounts', ['username'], unique=False)
    op.create_table('analytics_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('metric_period', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_lookup', 'analytics_cache', ['instagram_account_id', 'metric_type', 'metric_period'], unique=False)
    op.create_index(op.f('ix_analytics_cache_expires_at'), 'analytics_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_analytics_cache_id'), 'analytics_cache', ['id'], unique=False)
    op.create_table('api_rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('window_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('is_throttled', sa.Boolean(), nullable=True),
    sa.Column('throttle_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rate_limit_lookup', 'api_rate_limits', ['instagram_account_id', 'endpoint', 'window_start'], unique=False)
    op.create_index(op.f('ix_api_rate_limits_id'), 'api_rate_limits', ['id'], unique=False)
    op.create_table('insights_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('insights_data', sa.JSON(), nullable=False),
    sa.Column('ai_recommendations', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_cache_id'), 'insights_cache', ['id'], unique=False)
    op.create_table('instagram_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('saves_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('plays', sa.Integer(), nullable=True),
    sa.Column('ai_tags', sa.JSON(), nullable=True),
    sa.Column('ai_sentiment', sa.String(length=50), nullable=True),
    sa.Column('ai_content_themes', sa.JSON(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_metrics_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_posts_engagement_rate'), 'instagram_posts', ['engagement_rate'], unique=False)
    op.create_index(op.f('ix_instagram_posts_id'), 'instagram_posts', ['id'], unique=False)
    op.create_index(op.f('ix_instagram_posts_instagram_account_id'), 'instagram_posts', ['instagram_account_id'], unique=False)
    op.create_index(op.f('ix_instagram_posts_media_id'), 'instagram_posts', ['media_id'], unique=True)
    op.create_index(op.f('ix_instagram_posts_timestamp'), 'instagram_posts', ['timestamp'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_id'), 'webhook_logs', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_received_at'), 'webhook_logs', ['received_at'], unique=False)
    op.create_table('generated_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('storage_provider', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('source_post_ids', sa.JSON(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('generation_config', sa.JSON(), nullable=True),
    sa.Column('processing_time_seconds', sa.Integer(), nullable=True),
    sa.Column('suggested_caption', sa.Text(), nullable=True),
    sa.Column('suggested_hashtags', sa.JSON(), nullable=True),
    sa.Column('best_posting_time', sa.DateTime(), nullable=True),
    sa.Column('target_audience', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'APPROVED', 'REJECTED', 'PUBLISHED', 'FAILED', name='contentstatus'), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('predicted_engagement_rate', sa.Float(), nullable=True),
    sa.Column('predicted_reach', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('actual_engagement_rate', sa.Float(), nullable=True),
    sa.Column('actual_reach', sa.Integer(), nullable=True),
    sa.Column('published_post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ),
    sa.ForeignKeyConstraint(['published_post_id'], ['instagram_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_content_content_type'), 'generated_content', ['content_type'], unique=False)
    op.create_index(op.f('ix_generated_content_created_at'), 'generated_content', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_content_id'), 'generated_content', ['id'], unique=False)
    op.create_index(op.f('ix_generated_content_instagram_account_id'), 'generated_content', ['instagram_account_id'], unique=False)
    op.create_index(op.f('ix_generated_content_status'), 'generated_content', ['status'], unique=False)
    op.create_index(op.f('ix_generated_content_user_id'), 'generated_content', ['user_id'], unique=False)
    op.create_table('post_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('generated_content_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('post_type', sa.String(length=50), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('location_id', sa.String(length=255), nullable=True),
    sa.Column('collaborators', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'CANCELLED', name='schedulestatus'), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('instagram_post_id', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_content_id'], ['generated_content.id'], ),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_schedule_id'), 'post_schedule', ['id'], unique=False)
    op.create_index(op.f('ix_post_schedule_instagram_account_id'), 'post_schedule', ['instagram_account_id'], unique=False)
    op.create_index(op.f('ix_post_schedule_scheduled_time'), 'post_schedule', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_post_schedule_status'), 'post_schedule', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_schedule_status'), table_name='post_schedule')
    op.drop_index(op.f('ix_post_schedule_scheduled_time'), table_name='post_schedule')
    op.drop_index(op.f('ix_post_schedule_instagram_account_id'), table_name='post_schedule')
    op.drop_index(op.f('ix_post_schedule_id'), table_name='post_schedule')
    op.drop_table('post_schedule')
    op.drop_index(op.f('ix_generated_content_user_id'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_status'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_instagram_account_id'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_id'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_created_at'), table_name='generated_content')
    op.drop_index(op.f('ix_generated_content_content_type'), table_name='generated_content')
    op.drop_table('generated_content')
    op.drop_index(op.f('ix_webhook_logs_received_at'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_id'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index(op.f('ix_instagram_posts_timestamp'), table_name='instagram_posts')
    op.drop_index(op.f('ix_instagram_posts_media_id'), table_name='instagram_posts')
    op.drop_index(op.f('ix_instagram_posts_instagram_account_id'), table_name='instagram_posts')
    op.drop_index(op.f('ix_instagram_posts_id'), table_name='instagram_posts')
    op.drop_index(op.f('ix_instagram_posts_engagement_rate'), table_name='instagram_posts')
    op.drop_table('instagram_posts')
    op.drop_index(op.f('ix_insights_cache_id'), table_name='insights_cache')
    op.drop_table('insights_cache')
    op.drop_index(op.f('ix_api_rate_limits_id'), table_name='api_rate_limits')
    op.drop_index('idx_rate_limit_lookup', table_name='api_rate_limits')
    op.drop_table('api_rate_limits')
    op.drop_index(op.f('ix_analytics_cache_id'), table_name='analytics_cache')
    op.drop_index(op.f('ix_analytics_cache_expires_at'), table_name='analytics_cache')
    op.drop_index('idx_analytics_lookup', table_name='analytics_cache')
    op.drop_table('analytics_cache')
    op.drop_index(op.f('ix_instagram_accounts_username'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_user_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_next_sync_at'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_instagram_user_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_id'), table_name='instagram_accounts')
    op.drop_table('instagram_accounts')
    op.drop_index(op.f('ix_content_templates_id'), table_name='content_templates')
    op.drop_table('content_templates')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
